## ---- include = FALSE---------------------------------------------------------
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)

## ---- eval=FALSE--------------------------------------------------------------
#  # library(epitopes)
#  #
#  # # Download the full IEDB export into a given folder "XYZ"
#  # epitopes::get_IEDB(save_folder = "XYZ")
#  #
#  # # Extract only the linear B-cell epitopes from the IEDB export and save the
#  # # result to folder "ABC"
#  # epitopes <- epitopes::get_LBCE(data_folder = "XYZ",
#  #                                ncpus = parallel::detectCores() - 2,
#  #                                save_folder = "ABC")
#  #
#  # # Retrieve the relevant proteins and save them into the same folder "ABC"
#  # proteins <- epitopes::get_proteins(uids = unique(epitopes$protein_id),
#  #                                    save_folder = "ABC")
#  #
#  # # Retrieve a taxonomy list for all pathogens and save it into the same folder "ABC"
#  # taxonomy <- epitopes::get_taxonomy(uids = unique(c(epitopes$sourceOrg_id,
#  #                                                    epitopes$host_id)),
#  #                                    save_folder = "ABC")
#  

## ---- eval = FALSE------------------------------------------------------------
#  library(epitopes)
#  
#  epitopes <- readRDS("./data/epitopes.rds") # Generated by get_IEDB() -> get_LBCE()
#  proteins <- readRDS("./data/proteins.rds") # Generated by get_proteins()
#  taxonomy <- readRDS("./data/taxonomy.rds") # Generated by get_taxonomy()
#  
#  orgID <- 10376 # Taxonomy ID for the Epstein-Barr virus
#  ncpus <- parallel::detectCores() - 2
#  
#  peptides.list <- epitopes %>%
#    filter_epitopes(orgIDs        = orgID, # <--- Filter entries by organism ID
#                    tax_list      = taxonomy) %>%
#    consolidate_data(proteins,
#                     only_exact = FALSE, # <----- Also include 'epitope containing regions'
#                     ncpus = ncpus) %>%
#    extract_peptides(min_peptide = 8, # <-------- shortest labelled peptide considered (regardles of Class)
#                     max_epitope = 25) %>% # <--- longest positively-labelled entry considered
#    make_data_splits(proteins     = proteins,
#                     target_props = c(.25, .75), # <-- desired split proportions
#                     similarity_threshold = .6,  # <-- proteins more similar than this are always placed in the same split.
#                     ncpus = ncpus) %>%
#    calc_features(
#      # local features are calculated for the local windows and added to peptides.list$df
#      local.features = c("Entropy","MolWeight", "AAtypes", "Atoms", "AAC", "CTDC", "CTDD", "CTDT", "BLOSUM"),
#      # global features are calculated at the full protein level and added to peptides.list$proteins (needs a data join on df later, before training the models)
#      global.features = c("AAC", "DC", "CTDC", "CTDD", "CTDT", "CTriad", "SOCN", "Entropy", "MolWeight", "AAtypes"),
#      ncpus = ncpus)

## ---- eval=FALSE--------------------------------------------------------------
#  > names(peptides.list)
#  [1] "df"                "peptides"          "filter.attrs"      "consolidate.attrs" "peptide.attrs"
#  [6] "proteins"          "splits.attrs"      "feature.attrs"

