library(dplyr)
# library(epitopes) # Dev version

ncpus <- parallel::detectCores() - 1

# orgID <- 5693 # T. Cruzi
orgID <- 6282 # O. volvulus


epitopes <- readRDS("./data/epitopes.rds") # Generated by get_IEDB() followed by get_LBCE()
proteins <- readRDS("./data/proteins.rds") # Generated by get_proteins()
taxonomy <- readRDS("./data/taxonomy.rds") # Generated by get_taxonomy()


X <- epitopes %>%
  filter_epitopes(orgIDs        = orgID,
                  orgID_column  = "sourceOrg_id",
                  hostID_column = "host_id",
                  tax_list      = taxonomy) %>%
  consolidate_data(proteins, only_exact = FALSE, ncpus = ncpus) %>%
  mutate(Info_IsExact = sapply(Info_type, grepl, pattern = "Exact"),
         Info_IsExact = ifelse(is.na(Class), NA, Info_IsExact),
         Info_nPos = ifelse(is.na(Info_nPos), 0, Info_nPos),
         Info_nNeg = ifelse(is.na(Info_nNeg), 0, Info_nNeg)) %>%
  select(-Class, everything(), Class, -Info_type)


saveRDS(X, "./data/Ov_labelled_prots.rds")
