# this script uses the devel-next version of the epitopes package:
# > devtools::install_github("fcampelo/epitopes@devel-next", force = TRUE)
# > epitopes::install_bioc_dependencies(force = TRUE)

library(dplyr)
library(epitopes)

ncpus <- parallel::detectCores() - 1

trIDs <- c(10242, 10240, 2732527, 2732525, 2732007)
mpID  <- 10244

epitopes <- readRDS("./data/epitopes.rds") # Generated by get_IEDB() followed by get_LBCE()
proteins <- readRDS("./data/proteins.rds") # Generated by get_proteins()
taxonomy <- readRDS("./data/taxonomy.rds") # Generated by get_taxonomy()

X <- epitopes %>%
  filter_epitopes(orgIDs        = trID,
                  orgID_column  = "sourceOrg_id",
                  hostID_column = "host_id",
                  tax_list      = taxonomy) %>%
  consolidate_data(proteins, only_exact = FALSE, ncpus = ncpus) %>%
  extract_peptides(min_peptide = 6, max_epitope = 30) %>%
  make_data_splits(proteins    = proteins,
                   target_props = c(1/3,1/3,1/3),
                   split_names = paste0("CV", 1:3), #("training", "holdout"),
                   similarity_threshold = .5,
                   ncpus = ncpus) %>%
  calc_features(local.features = c("Entropy","MolWeight", "AAtypes", "Atoms",   # <--- local features are calculated for the 15-AA windows and added to peptides.list$df
                                   "AAC", "CTDC", "CTDD", "CTDT", "BLOSUM",
                                   "SOCN", "QSO", "ScalesGap")) %>%
  fit_model(CV.folds = paste0("CV", 1:3),
            #holdout.split = "holdout",
            ncpus = ncpus, return.model = "full")


newdata <- epitopes %>%
  filter_epitopes(orgIDs        = mpID,
                  orgID_column  = "sourceOrg_id",
                  hostID_column = "host_id",
                  tax_list      = taxonomy) %>%
  consolidate_data(proteins, only_exact = FALSE, ncpus = ncpus) %>%
  extract_peptides(min_peptide = 1, max_epitope = 200) %>%
  calc_features(local.features = c("Entropy","MolWeight", "AAtypes", "Atoms",   # <--- local features are calculated for the 15-AA windows and added to peptides.list$df
                                   "AAC", "CTDC", "CTDD", "CTDT", "BLOSUM",
                                   "SOCN", "QSO", "ScalesGap"))



# x <- peptides.list$Info_type
# a <- grepl("Exact Epitope", x)
# x[which(a)] <- "Exact Epitope"
# x[which(!a & !is.na(x))] <- "Epitope-Containing Region"
#
# peptides.list$Info_type <- unname(x)
#
# X <- peptides.list %>%
#   dplyr::select(Info_organism_id, Info_protein_id, Info_pos, Info_AA, Info_epitope_id,
#                 Info_type, Class)
#
# table(X$Class, X$Info_type)



# for (i in 1:20){
#   message("Fitting for i = ", i)
#   tmp <- peptides.list %>%
#     fit_model(CV.folds = paste0("CV", 1:5),
#               #holdout.split = "holdout",
#               ncpus = ncpus,
#               return.model = "none",
#               min.node.size = i)
#   res <- rbind(res,
#                data.frame(min.node.size = i,
#                           Var = names(tmp$model.perf[5:14]),
#                           Value = unlist(tmp$model.perf[5:14])))
# }
#
# library(ggplot2)
# ggplot(res, aes(x = min.node.size, y = Value, group = Var)) + geom_line() + facet_grid(Var~., scales = "free_y")
#

# TODO:
# - test splitting by peptides
# - make sure make_splits(is protected against empty splits)
# - add print/summary/plot routines
# - update Lucid.app graphical description
# - optional echoing mode
# - test unbalanced data-specific splitting functions for RF


# t1 <- Sys.time()
# message("Elapsed time: ", signif(t1 - t0, 3), " ", units(t1 - t0))
# saveRDS(peptides.list, savefile)
