library(dplyr)
library(epitopes)
ncpus <- parallel::detectCores() - 1

# Function to build local neighbourhoods for feature calculation
make_windows <- function(x, Class, window_size){
  imax    <- length(x)
  windows <- sapply(seq_along(x),
                    function(y){
                      idx <- (y - floor(window_size/2)):(y + floor(window_size/2))
                      if(any(idx <= 0))   idx <- idx[-which(idx <= 0)]
                      if(any(idx > imax)) idx <- idx[-which(idx > imax)]
                      paste(x[idx], collapse = "")
                    })
  return(windows)
}

# Function to determine class type (exact/approx)
get_type <- function(nPos,nNeg,type,Class){
  if (is.na(Class)) return(NA)
  x <- strsplit(nPos, split = ",")[[1]]
  y <- strsplit(nNeg, split = ",")[[1]]
  z <- strsplit(names(type), split = ",", fixed = TRUE)[[1]]
  if(length(z) == 0) return(NA)
  any.exact.pos <- any(as.numeric(x) > 0 & sapply(z, grepl,pattern="Exact"))
  any.exact.neg <- any(as.numeric(y) > 0 & sapply(z, grepl,pattern="Exact"))
  if (Class == 1)  return(ifelse(any.exact.pos, "Exact", "Approx"))
  if (Class == -1) return(ifelse(any.exact.neg, "Exact", "Approx"))
}

orgID    <- 6282    # O. volvulus

epitopes <- readRDS("./data/epitopes.rds") # Generated by get_IEDB() followed by get_LBCE()
proteins <- readRDS("./data/proteins.rds") # Generated by get_proteins()
taxonomy <- readRDS("./data/taxonomy.rds") # Generated by get_taxonomy()

t0 <- Sys.time()

X <- epitopes %>%
  filter_epitopes(orgIDs        = orgID,
                  orgID_column  = "sourceOrg_id",
                  hostID_column = "host_id",
                  tax_list      = taxonomy) %>%
  consolidate_data(proteins, only_exact = FALSE, ncpus = ncpus, set_positive = "any") %>%
  select(-Info_pubmed_id) %>%
  mutate(Info_nPos = ifelse(is.na(Info_nPos), 0, Info_nPos),
         Info_nNeg = ifelse(is.na(Info_nNeg), 0, Info_nNeg))

type <- character(nrow(X))
for (i in seq_along(type)) {
  type[i] <- get_type(nPos = X$Info_nPos[i],
                      nNeg = X$Info_nNeg[i],
                      type = X$Info_type[i],
                      Class = X$Class[i])
}
X$Info_type <- type

X <- X %>% group_by(Info_protein_id) %>%
  mutate(Info_window = make_windows(Info_AA, Class, window_size = 15)) %>%
  ungroup()

feats <- lapply(X$Info_window, epitopes:::extractLegacyFeatures, max.N = 1)

feats <- do.call(rbind, feats)
dim(X)

# Make splits
Y <- epitopes %>%
  filter_epitopes(orgIDs        = orgID,
                  orgID_column  = "sourceOrg_id",
                  hostID_column = "host_id",
                  tax_list      = taxonomy) %>%
  consolidate_data(proteins, only_exact = FALSE, ncpus = ncpus) %>%
  extract_peptides(min_peptide = 8, max_epitope = 25) %>%
  make_data_splits(proteins    = proteins,
                   target_props = rep(.2, 5),#c(1/3,1/3,1/3), #c(.7,.3), #
                   split_names = paste0("CV", 1:5), #c("training", "holdout"), #
                   similarity_threshold = .6,
                   ncpus = ncpus)

Y <- Y$df %>%
  group_by(Info_protein_id) %>%
  summarise(Info_split = first(Info_split))

X <- X %>% left_join(Y, by = "Info_protein_id") %>% select(starts_with("Info"), Class, everything())

write.csv(X, "./data/Ov_fullprots.rds")
