#' Extract data summary
#'
#' Summarise a peptides list and extracts number of peptides, groups and
#' observations under each class
#'
#'
#' @param peptides.list peptides.list object returned by [make_data_splits()].
#' @param uid taxononmy id to extract a subset of the data. `NULL` to
#' summarise the entire dataset
#' @param tax_list taxonomy list (generated by [get_taxonomy()])
#' @param min_pept_grp minimum number of peptides in a group to be considered
#' @param redundancy_threshold similarity threshold in the (0,1) interval for
#' redundancy removal. If a nonzero value is passed, it uses
#' [moses::extract_clusters_cdhit()] for clustering the peptides at the desired
#' similarity threshold and uses only one representative example per cluster
#' when calculating the summary statistics.
#'
#' @return 1-row data frame with summary information.
#'
#' @importFrom rlang .data
#' @importFrom dplyr %>%
#'
#' @author Felipe Campelo (\email{fcampelo@@gmail.com})
#'
#' @export
#'
get_data_summary <- function(peptides.list,
                             uid = NULL,
                             tax_list = NULL,
                             min_pept_grp = 1,
                             redundancy_threshold = 0){

  # ========================================================================== #
  # Sanity checks and initial definitions

  assertthat::assert_that(is.list(peptides.list),
                          all(c("df", "peptides", "proteins") %in% names(peptides.list)),
                          is.numeric(uid) | is.character(uid) | is.null(uid),
                          is.list(tax_list) | is.null(tax_list),
                          ifelse(is.null(uid), TRUE, !is.null(tax_list)),
                          assertthat::is.count(min_pept_grp),
                          is.numeric(redundancy_threshold),
                          length(redundancy_threshold) == 1,
                          redundancy_threshold >= 0,
                          redundancy_threshold <= 1)

  # ========================================================================== #

  if(!is.null(uid)){
    peptides.list <- taxonomy_filter(peptides.list = peptides.list,
                                     orgIDs        = uid,
                                     tax_list      = tax_list)
  }

  if(redundancy_threshold > 0){
    tmp <- peptides.list$peptides %>%
      dplyr::select(IDs  = "Info_PepID",
                    SEQs = "Info_peptide")
    mycl <- moses::extract_clusters_cdhit(X = tmp,
                                          diss_threshold = redundancy_threshold,
                                          vrb = FALSE,
                                          par.list = list(kmerSize = NULL,
                                                          min_length = min(sapply(tmp$SEQs, nchar)),
                                                          s = 1, G = 1))
    tmp <- tmp %>%
      dplyr::left_join(mycl$clusters, by = c("IDs" = "ID")) %>%
      dplyr::group_by(.data$Cluster) %>%
      dplyr::summarise(IDs = dplyr::first(.data$IDs))

    peptides.list$df <- peptides.list$df %>%
      dplyr::filter(.data$Info_PepID %in% tmp$IDs)

    peptides.list$peptides <- peptides.list$peptides %>%
      dplyr::filter(.data$Info_PepID %in% tmp$IDs)

    peptides.list$proteins <- peptides.list$proteins %>%
      dplyr::filter(.data$Info_protein_id %in% unique(peptides.list$peptides$Info_protein_id))
  }

  grps <- peptides.list$peptides %>%
    dplyr::group_by(.data$Info_group) %>%
    dplyr::summarise(Pos   = sum(.data$Class == 1) > min_pept_grp,
                     Neg   = sum(.data$Class == -1) > min_pept_grp,
                     .groups = "drop")

  data.frame(UID      = ifelse(is.null(uid), "All", uid),
             Pos.pept = sum(peptides.list$peptides$Class == 1),
             Neg.pept = sum(peptides.list$peptides$Class == -1),
             Pos.AA   = sum(peptides.list$df$Class == 1),
             Neg.AA   = sum(peptides.list$df$Class == -1),
             Groups   = length(unique(peptides.list$df$Info_group)),
             Prots    = length(unique(peptides.list$df$Info_protein_id)),
             LargeGrp.HasOnlyPos  = sum(grps$Pos) - sum(grps$Pos & grps$Neg),
             LargeGrp.HasOnlyNeg  = sum(grps$Neg) - sum(grps$Pos & grps$Neg),
             LargeGrp.HasPosNeg   = sum(grps$Pos & grps$Neg))
}

