#' Extract data summary
#'
#' Summarise a peptides list and extracts number of peptides, groups and
#' observations under each class
#'
#'
#' @param peptides.list peptides.list object returned by [make_data_splits()].
#' @param uid taxononmy id to extract a subset of the data. `NULL` to
#' summarise the entire dataset
#' @param tax_list taxonomy list (generated by [get_taxonomy()])
#'
#' @return 1-row data frame with summary information.
#'
#' @author Felipe Campelo (\email{fcampelo@@gmail.com})
#'
#' @export
#'
get_data_summary <- function(peptides.list, uid = NULL, tax_list = NULL, min_pept_grp = 1){

  # ========================================================================== #
  # Sanity checks and initial definitions

  assertthat::assert_that(is.list(peptides.list),
                          all(c("df", "peptides", "proteins") %in% names(peptides.list)),
                          is.numeric(uid) | is.character(uid) | is.null(uid),
                          is.list(tax_list) | is.null(tax_list),
                          ifelse(is.null(uid), TRUE, !is.null(tax_list)))

  # ========================================================================== #

  if(!is.null(uid)){
    peptides.list <- taxonomy_filter(peptides.list = peptides.list,
                                     orgIDs        = uid,
                                     tax_list      = tax_list)
  }

  grps <- peptides.list$peptides %>%
    group_by(Info_group) %>%
    summarise(Pos = sum(Class == 1) > min_pept_grp,
              Neg = sum(Class == -1) > min_pept_grp,
              .groups = "drop")

  data.frame(UID      = ifelse(is.null(uid), "All", uid),
             Pos.pept = sum(peptides.list$peptides$Class == 1),
             Neg.pept = sum(peptides.list$peptides$Class == -1),
             Pos.AA   = sum(peptides.list$df$Class == 1),
             Neg.AA   = sum(peptides.list$df$Class == -1),
             Groups   = length(unique(peptides.list$df$Info_group)),
             Grp.HasPos = sum(grps$HasPos),
             Grp.HasNeg = sum(grps$HasNeg))
}
