#' Define data splits for predictive modelling.
#'
#' Split the data returned by [extract_labelled_data()] into
#' non-overlapping subsets. Proteins with similarities higher than
#' a predefined threshold are always placed in the same split to prevent data
#' leakage. See [moses::make_splits_constructive()] and
#' [moses::make_splits_rand_refine()] for details.
#'
#' @param peptides.list list object returned by [extract_labelled_data()], containing
#'        the data frame of windowed epitope data (**$df**), the data frame of
#'        individual peptides (**$peptides**) and the data frame of proteins
#'        (**$proteins**).
#' @param delta vector of desired split proportions (must add up to one). It
#'        is useful (but not mandatory) to use a vector that is sorted
#'        in decreasing order.
#' @param w vector of weights for function aggregation. Must be of
#'          length 3 and add to 1. All weights must be non-negative. See
#'          package `moses` for details.
#'          `w[1]`: weight of the objective to obey desired split proportions;
#'          `w[2]`: weight of the objective to distribute classes proportionally between splits;
#'          `w[3]`: weight of the objective to maximise within-splits diversity.
#'          Notice that `w[3]` is ignored if `split_mode == "rand"` (in which case
#'          `w[1]` and `w[2]` are scaled internally so that `w[1] + w[2] = 1`
#'          while keeping their relative proportions).
#' @param split_names optional, vector of names to be given to each split.
#' @param split_mode mode of splitting. Use "constructive" for a deterministic
#' constructive heuristic (calling [moses::make_splits_constructive()]) or
#' "rand" for a randomised heuristic (calling [moses::make_splits_rand_refine()]).
#' Using "rand" is necessary if you plan to use model development strategies in
#' which some splits need to be redefined, e.g., in repeated cross-validation.
#' @param similarity_threshold similarity threshold for grouping observations.
#'        \eqn{1 - similarity_threshold} is passed to [CellaRepertorium::cdhit()] as
#' @param target_id vector of lower-level taxonomy ids (integer or character)
#'        that the splitting strategy should try to prioritise
#'        distributing across splits (useful, e.g., if generating splits at a
#'        higher taxonomic level for later re-use at a lower level).
#' @param tax_list taxonomy list (generated by [get_taxonomy()]). Only used if
#'        `target_id` is not `NULL`.
#' @param save_folder path to folder for saving the results. It will save the
#' results as file *peptides_list.rds* (overwriting if necessary)
#' @param ncpus positive integer, number of cores to use.
#' @param cdhit.par.list further parameters to be passed down to
#' [CellaRepertorium::cdhit()]. Please check that function for details.
#'
#' @return Updated `peptides.list` with dataframes containing 2 additional columns,
#' `Info_group` (cluster id returned by CDHIT) and `Info_split` (which allocates
#' groups to different splits.
#'
#' If the splitting is impossible (e.g., if the number of clusters is smaller
#' than the desired number of splits) the function throws a warning and returns
#' the list object returned by [CellaRepertorium::cdhit()].
#'
#' @author Felipe Campelo (\email{f.campelo@@aston.ac.uk})
#'
#' @importFrom dplyr %>%
#' @importFrom rlang .data
#'
#' @export
#'

make_data_splits <- function(peptides.list,
                             delta,
                             w = c(.5, .4, .1),
                             split_names  = NULL,
                             split_mode   = "rand",
                             similarity_threshold = .7,
                             target_id = NULL,
                             tax_list = NULL,
                             save_folder = NULL,
                             ncpus       = 1,
                             cdhit.par.list = list(s = 0.5)){


  # ========================================================================== #
  # Sanity checks and initial definitions

  assertthat::assert_that(is.list(peptides.list),
                          all(c("df", "peptides", "proteins") %in% names(peptides.list)),
                          is.numeric(delta), length(delta) > 1,
                          all(delta > 0), sum(delta) == 1,
                          is.null(split_names) || is.character(split_names),
                          is.null(split_names) || length(split_names) == length(delta),
                          is.character(split_mode) && length(split_mode) == 1,
                          split_mode %in% c("constructive", "rand"),
                          is.numeric(similarity_threshold),
                          length(similarity_threshold) == 1,
                          similarity_threshold > 0, similarity_threshold < 1,
                          is.vector(delta), is.numeric(delta),
                          sum(delta) == 1,
                          is.numeric(w), length(w) == 3, all(w >= 0), sum(w) == 1,
                          is.null(save_folder) | (is.character(save_folder)),
                          is.null(save_folder) | length(save_folder) == 1,
                          assertthat::is.count(ncpus))

  delta <- sort(delta, decreasing = TRUE)
  if (is.null(split_names)) split_names <- sprintf("split_%02d_%02d",
                                                   seq_along(delta),
                                                   round(100*delta))
  # ========================================================================== #

  # Remove pre-existing groupings
  df <- peptides.list$df %>%
    dplyr::select(-dplyr::starts_with("Info_group"),
                  -dplyr::starts_with("Info_split"))
  peptides <- peptides.list$peptides %>%
    dplyr::select(-dplyr::starts_with("Info_group"),
                  -dplyr::starts_with("Info_split"))
  proteins <- peptides.list$proteins %>%
    dplyr::select(-dplyr::starts_with("Info_group"),
                  -dplyr::starts_with("Info_split"))

  # Build reduced dataset of proteins
  tmpPep <- peptides %>%
    dplyr::group_by(.data$Info_protein_id) %>%
    dplyr::summarise(dplyr::across(dplyr::everything(), dplyr::first))

  myprots <- proteins %>%
    dplyr::left_join(tmpPep,
                     by = "Info_protein_id") %>%
    dplyr::filter(!is.na(.data$Info_organism_id)) %>%
    dplyr::select(IDs   = "Info_protein_id",
                  SEQs  = "Info_protein_sequence",
                  TXIDs = "Info_organism_id")

  # Find groupings using CDHIT
  if(!is.null(cdhit.par.list)){
    mycl <- moses::extract_clusters_cdhit(myprots,
                                          diss_threshold = 1 - similarity_threshold,
                                          ncpus = ncpus,
                                          par.list = cdhit.par.list,
                                          vrb = FALSE)
  } else {
    mycl <- moses::extract_clusters_cdhit(myprots,
                                          diss_threshold = 1 - similarity_threshold,
                                          ncpus = ncpus,
                                          vrb = FALSE)
  }

  if(length(unique(mycl$cl.df$cluster_idx)) < length(delta)){
    warning("Impossible to divide data into ", length(delta),
            " splits at similarity level ", similarity_threshold,
            ".\nTry a higher similarity threshold.\nReturning NULL.")
    return(mycl)
  }

  # Check how many positive / negative examples per group
  Y <- df %>%
    dplyr::left_join(mycl$clusters, by = c("Info_protein_id" = "ID")) %>%
    dplyr::rename(Group = "Cluster") %>%
    dplyr::group_by(.data$Group) %>%
    dplyr::summarise(nPos    = sum(.data$Class == 1),
                     nNeg    = sum(.data$Class == -1),
                     txids   = list(unique(sapply(.data$Info_sourceOrg_id, txid_boildown))),
                     protids = list(unique(.data$Info_protein_id)))

  # Build groups x classes matrix
  C <- as.matrix(Y[, 2:3])


  # Initial splitting (target group only) first, if needed
  if(!is.null(target_id)){

    # Get all ids under the target_id taxon
    ids <- tax_list[which(sapply(tax_list,
                                 function(a, id){
                                   any(c(a$Taxonomy$UID, a$UID) == id)
                                 },
                                 id = target_id))]
    ids <- sapply(ids, function(a) a$UID)


    # Get which groups have observations from target_id
    idx <- which(sapply(Y$txids,
                        function(x, ids) any(x %in% ids),
                        ids = ids))

    # Get reduced matrix of class counts for only the selected groups
    C0 <- C[idx, ]
    colnames(C0) <- paste0("class.", colnames(C0))

    # Get split allocations for reduced matrix C0
    if(split_mode == "constructive"){
      X <- moses::make_splits_constructive(C = C0, delta = delta, w = w)
    } else {
      w <- w[1:2] / sum(w[1:2])
      X <- moses::make_splits_rand_refine(C = C0, delta = delta, w = w)
    }

    # Incorporate partial allocation into a full initial allocation matrix
    X0 <- matrix(0, nrow = length(delta), ncol = nrow(C))
    X0[, idx] <- X

    # Summarise partial allocation
    alloc0 <- X0 %*% C
    target_id_groups <- idx

  } else {
    X0 <- NULL
    alloc0 <- NULL
    target_id_groups <- NULL
  }

  # Get full split allocations
  C1 <- C
  colnames(C1) <- paste0("class.", colnames(C1))
  if(split_mode == "constructive"){
    X <- moses::make_splits_constructive(C = C1, delta = delta, w = w, X0 = X0)
  } else {
    w <- w[1:2] / sum(w[1:2])
    X <- moses::make_splits_rand_refine(C = C1, delta = delta, w = w, X0 = X0)
  }

  allocF <- X %*% C

  x <- apply(X, MARGIN = 2, FUN = function(z) which(z == 1))
  Y <- Y %>%
    dplyr::mutate(Info_split = split_names[x]) %>%
    dplyr::select("Info_split",
                  Info_group = "Group",
                  "protids",
                  "txids")

  Y <- lapply(1:nrow(Y), function(i, Y){
    data.frame(Info_split = Y$Info_split[i],
               Info_group = Y$Info_group[i],
               Info_protein_id = unlist(Y$protids[i]))},
    Y = Y) %>%
    dplyr::bind_rows()

  # Update list and return

  peptides.list$df <- df %>%
    dplyr::left_join(Y, by = "Info_protein_id") %>%
    dplyr::select(dplyr::starts_with("Info"),
                  "Class",
                  dplyr::everything())

  peptides.list$peptides <- peptides %>%
    dplyr::left_join(Y, by = "Info_protein_id") %>%
    dplyr::select(dplyr::starts_with("Info"), "Class", dplyr::everything())

  peptides.list$proteins <- proteins %>%
    dplyr::left_join(Y, by = "Info_protein_id") %>%
    dplyr::select(dplyr::starts_with("Info"), dplyr::everything())

  peptides.list$splits.attrs <- list(
    delta                = delta,
    w                    = w,
    similarity_threshold = similarity_threshold,
    cdhit.par.list = cdhit.par.list,
    target_id = target_id)

  peptides.list$splits.summary <- list(
    target_id = target_id,
    target_id_groups = target_id_groups,
    target_id_alloc_summary = alloc0,
    final_alloc_summary    = allocF
  )

  return(peptides.list)

}
