#' Filter peptides by taxonomy and host
#'
#' Filters an peptides dataframe by source organism and/or host IDs.
#'
#' Taxonomic filtering works hierarchically - e.g., if a genus id is passed in
#' `orgIDs`, all species under that genus are removed.
#' `removeIDs` is generally used to censor out one or more subgroups under those
#' listed in `orgIDs`. For instance, if we wanted to get data for all
#' orthopoxvirus (txID:10242) except Variola (txID:10255) we would make
#' `orgIDs = 10242` and `removeIDs = 10255`.
#'
#' @param df a data frame containing peptide data (returned by
#' [get_LBCE()] or [consolidate_data()]). Only one of `df` or `peptides.list`
#' should be provided.
#' @param peptides.list list object returned by [extract_labelled_data()].
#' Only one of `df` or `peptides.list` should be provided.
#' @param orgIDs vector of organism taxon IDs to retain.
#' @param hostIDs vector of host taxon IDs to retain.
#' @param removeIDs vector of organism taxon IDs to remove.
#' @param orgID_column name of the column in `df` containing the source organism IDs
#' @param hostID_column name of the column in `df` containing the host IDs
#' @param tax_list taxonomy list (generated by [get_taxonomy()])
#'
#' @return data frame with peptide data filtered by the criteria in **orgIDs**,
#' **hostIDs** and **removeIDs**.
#'
#' @author Felipe Campelo (\email{f.campelo@@aston.ac.uk})
#'
#' @export
#'

taxonomy_filter <- function(df            = NULL,
                            peptides.list = NULL,
                            tax_list      = NULL,
                            orgIDs        = NULL,
                            hostIDs       = NULL,
                            removeIDs     = NULL,
                            orgID_column  = ifelse(is.null(df), "Info_organism_id", "sourceOrg_id"),
                            hostID_column = ifelse(is.null(df), "Info_host_id", "host_id")) {

  # ========================================================================== #
  # Sanity checks and initial definitions
  id_classes <- c("NULL", "numeric", "integer", "character")
  checkIDs <- function(ids){
    if(!is.null(ids) && any(is.na(ids))) {
      ids <- ids[-is.na(ids)]
      if(length(ids) == 0) ids <- NULL
    }
    return(ids)
  }

  orgIDs    <- checkIDs(orgIDs)
  hostIDs   <- checkIDs(hostIDs)
  removeIDs <- checkIDs(removeIDs)

  assertthat::assert_that(
    xor(is.null(df), is.null(peptides.list)),
    is.null(df) | is.data.frame(df),
    is.null(peptides.list) | is.list(peptides.list),
    is.null(peptides.list) | all(c("df", "peptides", "proteins") %in% names(peptides.list)),
    class(orgIDs)    %in% id_classes,
    class(hostIDs)   %in% id_classes,
    class(removeIDs) %in% id_classes,
    is.character(orgID_column), length(orgID_column) == 1,
    is.character(hostID_column), length(hostID_column) == 1,
    is.list(tax_list))

  if(is.data.frame(df)) return(taxonomy_filter_df(df, tax_list,
                                                  orgIDs, hostIDs, removeIDs,
                                                  orgID_column, hostID_column))

  if(is.list(peptides.list)) return(taxonomy_filter_list(peptides.list, tax_list,
                                                       orgIDs, hostIDs, removeIDs,
                                                       orgID_column, hostID_column))

}
